---
# Spring Setting
spring:
  profiles: default

  # JPA
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    #properties:
    #
    #  hibernate.dialect: org.hibernate.dialect.H2Dialect
    #  hibernate.show_sql: true
    #  hibernate.hbm2ddl.auto: create
    #hibernate:
    #  naming:
    #    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #  ddl-auto: create
    #  use-new-id-generator-mappings: true # 새 버전의 ID 옵션
    #show-sql: true # SQL 보기

# datasource Setting
datasource:
  demo:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://211.239.124.237:17402/demo?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul&rewriteBatchStatements=true&allowMultiQueries=true
    username: riley
    password: kai0114#
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    minimum-idle: 10 # same initial-size
    maximum-pool-size: 10
    pool-name: Module-Domain
    max-wait: 1000
    initial-size: 10
    connection-init-sql: /* Module-Domain (local) deomo New Connection Pool Create */ SELECT 1
